name: NPM publish CD workflow 1

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs: 
      release:
        description: "Make actual release (push in git and publish and npm"
        default: false
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: npm ci
    - run: npm run build
